language: go

go: 1.3.3

install:
  - ./tasks/ci/install.sh

script:
  - ./tasks/ci/run_tests.sh
  - ./tasks/ci/build_frontends.sh
  - ./tasks/ci/check_gen.sh --force
  - ./tasks/ci/check_fmt.sh --force

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3e692a5224c8490f19bd
    on_success: change
    on_failure: always
    on_start: false
